version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=http://localhost:3001
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_BASE_URL=https://api.themoviedb.org/3
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
